name: Destroy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        type: environment
        required: true
jobs:
  terraform-destroy:
    runs-on: ubuntu-latest
    name: Destroy
    environment:
      name: ${{ inputs.environment }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Workspace
        id: select-environment
        working-directory: ./terraform
        env:
          ENVIRONMENT: ${{ inputs.environment }}
        run: terraform workspace select $ENVIRONMENT

      - name: Terraform Destroy
        id: apply
        working-directory: ./terraform
        run: terraform destroy -auto-approve