name: Provision EC2 Instance with Terraform

on: [push]

jobs:
  terraform-staging-plan:
    runs-on: ubuntu-latest
    name: Plan staging

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Staging
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select staging

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan


  terraform-staging-deploy:
    runs-on: ubuntu-latest
    name: Deploy staging
    needs: [terraform-staging-plan]
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Staging
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select staging

      - name: Terraform Apply
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve


  terraform-green-plan:
    runs-on: ubuntu-latest
    name: Plan green
    needs: [terraform-staging-deploy]
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Green
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select green

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan


  terraform-green-deploy:
    runs-on: ubuntu-latest
    name: Deploy green
    needs: [terraform-green-plan]
    environment:
      name: green

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Green
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select green

      - name: Terraform Apply
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

  terraform-blue-plan:
    runs-on: ubuntu-latest
    name: Plan blue
    needs: [ terraform-staging-deploy ]
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Blue
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select blue

      - name: Terraform Plan
        id: plan
        working-directory: ./terraform
        run: terraform plan


  terraform-blue-deploy:
    runs-on: ubuntu-latest
    name: Deploy blue
    needs: [ terraform-blue-plan ]
    environment:
      name: blue

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Blue
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select blue

      - name: Terraform Apply
        id: apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

  terraform-staging-destroy:
    runs-on: ubuntu-latest
    name: Destroy staging
    needs: [ terraform-staging-deploy ]
    environment:
      name: staging

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Staging
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select staging

      - name: Terraform Destroy
        id: apply
        working-directory: ./terraform
        run: terraform destroy -auto-approve


  terraform-green-destroy:
    runs-on: ubuntu-latest
    name: Destroy green
    needs: [ terraform-green-deploy ]
    environment:
      name: green

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Green
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select green

      - name: Terraform Destroy
        id: apply
        working-directory: ./terraform
        run: terraform destroy -auto-approve

  terraform-blue-destroy:
    runs-on: ubuntu-latest
    name: Destroy blue
    needs: [ terraform-blue-deploy ]
    environment:
      name: blue

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        id: init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Select Blue
        id: select-environment
        working-directory: ./terraform
        run: terraform workspace select blue

      - name: Terraform Destroy
        id: apply
        working-directory: ./terraform
        run: terraform destroy -auto-approve
